[server]
# Disable file watcher to prevent the "dictionary changed size during iteration" error
fileWatcherType = "none"

# Optional: Set other server configurations
port = 8502
headless = false

[theme]
# Optional: Set theme colors
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
# Optional: Disable automatic browser opening
gatherUsageStats = false
